### ISSUE TITLE
Camera Transform glitch

### ISSUE THREAD

**Issue by digumx** [CodeCancer/ProjectReticle#12]
In the latest build at [CodeCancer/ProjectReticle:master](https://github.com/CodeCancer/ProjectReticle),  camera transformations do not work as expected. There are two main problems:

 -  Translation and rotation are inverted, translating forward moves camera back, while rotating left actually rotates camera right.
 -  Rotation axis does not pass through view space origin, but instead always passes through world space origin.

### Links to test case:

Fork/clone latest [ReticleLinuxTest:master](https://guthub.com/digumx/ReticleLinuxTest) and link to latest [CodeCancer/ProjectReticle:master](https://github.com/CodeCancer/ProjectReticle) to set up test case. Remember to change the reticle root directory and the path to asset file in main.cpp. 

### The test case and bug description:

1. Import a single asset file into a `RetiSceneObject`.
1. Translate it to (0, 0, -10).
1. Use arrow keys, a loop wait of 5 milliseconds (implemented with `this_thread::sleep_for(...)` from `chrono`, forward and backward mapping to translating camera by 0.003 along z, and left and right to rotating by 0.003 with axis y. (The bug is probably agnostic to these details.)
1. Build and run.
1. Move camera with up key till it clips into model.
1. Rotate using left or right keys.

**Expected behavior:** Camera continues to clip model and rotates in place.

**Behavior obtained:** Camera moves laterally out of the model in a circular arc of large radius, ceasing to clip the model.

**Note:**

 -  Depending upon asset file used, an additional scale may need to be applied to the `RetiSceneObject`.
 -  Also, problem in bullet 1 can easily be understood if one notices the signs of the translations/angles used to move the camera. 

_Sent from my Asus ASUS_Z00LD using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by technosap** [comment]
## Problem is confirmed

I saw the same behavior this morning when implementing Reticle Based CLI tool

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by digumx** [comment]
Created branch [digumx/ProjectReticle:Bugfix-Isue12](https://github.com/digumx/ProjectReticle/tree/Bugfix-Issue12) to work on fixing this issue.

**Comment by digumx** [comment]
Branch [digumx/ProjectReticle:Bugfix-Issue#12](https://github.com/digumx/ProjectReticle/tree/Bugfix-Issue%2312) contains a solution that I consider suboptimal in terms of performance and code complexity. Please see [digumx/ProjectReticle:Bugfix-Issue12-Take2](https://github.com/digumx/ProjectReticle/tree/Bugfix-Issue12-Take2) instead.

**Comment by digumx** [comment]
The [latest PR from digumx/ProjectReticle:Bugfix-Issue12-Take2](https://github.com/CodeCancer/ProjectReticle/pull/13) solves this issue. @technosap  please review and close issue.

**Comment by digumx** [comment]
Note: a better test of the bug and the fix is at [digumx/ReticleLinuxTest:Take2](https://github.com/digumx/ReticleLinuxTest/tree/Take2). @technosap , U could use it to test the fix.

**Comment by technosap** [comment]
The fix is complete and works.
