### ISSUE TITLE
Black Chair Bug

### ISSUE THREAD

**Issue by digumx** [CodeCancer/ProjectReticle#14]
Recently, I noticed a worrying bug while trying to import and render a chair asset file in the .3DS file format. The visual manifestation of the bug was that the chair was rendered completely in black.

### Bug Description:

The bug can be detected using the latest master branch build (latest commit 836b8f5) of [ReticleLinuxTest](https://github.com/digumx/ReticleLinuxTest). 

When using the attached asset file, a 3D model of a chair with texturing in the .3DS format, and loading it into obj2 (line excerpt: `RetiSceneObject obj2("/home/digumx/Models/Chair/Armchair.3DS");`, filepath may vary), Reticle renders it as a black chair:

![screenshot_2017-07-23_23-44-42](https://user-images.githubusercontent.com/29953130/28501846-592147e2-7002-11e7-8892-8c377d7a99ba.png "Screenshot of the bug")

### Useful files:

 -  Log file: [ReticleLog.txt](https://github.com/CodeCancer/ProjectReticle/files/1168306/ReticleLog.txt)
 -  Asset file: [Chair.zip](https://github.com/CodeCancer/ProjectReticle/files/1168308/Chair.zip)

### Note:

 -  I downloaded the above asset file from a free online site for Assets. It shall only be used for testing and bugifixing.
 -  Due to errors in capitalization of filenames linking to textures in the .3DS files, I had to rename the texture files so that the asset would load properly with the textures in other (mainly assimp_viewer) asset loaders. The changed version is attached here.

**Comment by digumx** [comment]
The merger of [PR#15](https://github.com/CodeCancer/ProjectReticle/pull/15) into master should fix this.
@technosap review this, (pull from master), and if u find the bug is gone, close this Issue or else make a comment here.
_Note:_ Using a file additional to the one used for bug detection(Attached above) may be useful.

**Comment by technosap** [comment]
Okay I will test it this evening.

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by technosap** [comment]
Works
