### ISSUE TITLE
Review Liscence

### ISSUE THREAD

**Issue by digumx** [CodeCancer/ProjectReticle#2]
**_URGENT_**

The license for Reticle is the MIT Licence. Is it compatible with the licenses of the following projects used under Reticle?

 -  stb_image
 -  glm
 -  assimp

@technosap @Ani-98 Please look into this.

**Comment by digumx** [comment]
Add these to the list:

 -  glfw
 -  glew
I checked that the following use versions of MIT License and hence are clear:

 -  stb_image
 -  glm
 
I am unsure about: 

 -  assimp

**Comment by digumx** [comment]
@technosap confirm if including the assimp license in our license clears our use of it.

_Sent from my Asus ASUS_Z00LD using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by technosap** [comment]
Please check the link below to clear all issues regarding licenses:
https://softwareengineering.stackexchange.com/questions/121998/mit-vs-bsd-vs-dual-license

assimp is BSD (3-clause) license so it can be used under MIT License

**Comment by technosap** [comment]
@digumx GLFW and GLEW usage is okay as long as you don't say you made wrote it.

**Comment by technosap** [comment]
http://www.glfw.org/license.html

https://github.com/nigels-com/glew
