### ISSUE TITLE
SegFault on Assimp Branch

### ISSUE THREAD

**Issue by technosap** [CodeCancer/ProjectReticle#6]
When using a 3DS file (https://archive3d.net/?a=download&id=b2628d18) which was UV mapped in Blender and Scaled to 0.1%, the program runs effectively when 3DS is scale transformed to 5x. But after successful execution, it gives a Segmentation fault as Output

System Info:
`$ glxinfo | grep "OpenGL version"`

Output:
```
OpenGL vendor string: NVIDIA Corporation  
OpenGL renderer string: GeForce 940M/PCIe/SSE2  
OpenGL core profile version string: 4.5.0 NVIDIA 375.66  
OpenGL core profile shading language version string: 4.50 NVIDIA  
OpenGL core profile context flags: (none)  
OpenGL core profile profile mask: core profile  
OpenGL core profile extensions:  
OpenGL version string: 4.5.0 NVIDIA 375.66  
OpenGL shading language version string: 4.50 NVIDIA  
OpenGL context flags: (none)  
OpenGL profile mask: (none)  
OpenGL extensions:  
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 375.66  
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20  
OpenGL ES profile extensions:  
```
SYSTEM REPORT ATTACHED
[hardinfo_report.html.txt](https://github.com/CodeCancer/ProjectReticle/files/1151205/hardinfo_report.html.txt)

**Comment by digumx** [comment]
I'll attach the .3ds file in question here, along with the original log, just for future reference.
[Files.zip](https://github.com/CodeCancer/ProjectReticle/files/1151278/Files.zip)

**Comment by digumx** [comment]
I've identified that, erratically, a similar problem occurs in master as well. However, running with master dumped the core-dump to stdout, which I've copy pasted and attached.
[CoreDumpLog.txt](https://github.com/CodeCancer/ProjectReticle/files/1151294/CoreDumpLog.txt)

@technosap Could u confirm if this happens on ur machine too?

**Comment by digumx** [comment]
Ok, so iv'e pushed latest commits to both [Bugfix-Issue6(PR7)](https://github.com/CodeCancer/ProjectReticle/pull/7) and [PullRequest4](https://github.com/CodeCancer/ProjectReticle/pull/4), to fix the issue. @technosap , review if the commits actually solve it.

**Comment by digumx** [comment]
Ok, it is confirmed that the problem had been solved in the aforementioned commit. The bug has now been removed from master branch by merging all commits from [PR#4](https://github.com/CodeCancer/ProjectReticle/pull/4) and [PR#5](https://github.com/CodeCancer/ProjectReticle/pull/5) through [PR#10](https://github.com/CodeCancer/ProjectReticle/pull/10). Closing issue.
